### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder106972153/source: no such file or directory

### ISSUE THREAD

**Issue by antimalbn** [synesthesiam/docker-mozillatts#14]
COPY failed: stat /var/lib/docker/tmp/docker-builder106972153/source: no such file or directory

we are getting this error when try to build docker image, please suggest

**Comment by synesthesiam** [comment]
Thanks for catching this; I just pushed up a fix. Creating a directory named `source` (empty) should be enough. If you have a file named `TTS.tar.gz` in that directory, it's used for the MozillaTTS source code instead of doing `git clone`.

**Comment by antimalbn** [comment]
Thanks for quick reply. I tried latest code but still getting below error 

Step 23/28 : COPY model/${LANGUAGE}/ /app/model/
COPY failed: stat /var/lib/docker/tmp/docker-builder002504544/model/en: no such file or directory

**Comment by synesthesiam** [comment]
This needs to be clearer in the README. I don't include any models in the repo, so you'll need to [download one](https://github.com/mozilla/TTS/wiki/Released-Models).

You need to put `config.json`, `checkpoint_<number>.pth.tar`, and `scale_stats.npy` into the `model/en` directory (assuming you're doing English).

If you want to add a vocoder too, create the directory `model/en/vocoder` and copy the corresponding vocoder files into it (`config.json`, `checkpoint_<number>.pth.tar`, and (optionally) `scale_stats.npy`).

**Comment by antimalbn** [comment]
sorry i missed that part 
thankyou for help, it worked.

**Comment by antimalbn** [comment]
thanks
